version: '1.0'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - name=value
        
    container_name: "test-code-web-qtasnim"
    ports:
      - 4000:4000
    volumes:
      - '/usr/src/admin-dasboard'
    command: "npm run dev"
